### ISSUE TITLE
[BUG] Borders do not work for NPCs in SWADE

### ISSUE THREAD

**Issue by Zamrod** [p4535992/token-factions#4]
**Module Version:** v0.2.16

**Describe the bug**
Token HUD does not appear at all and the borders do not appear for NPCs. The following error appears in the console:
```
foundry.js:316 
        
       TypeError: app.object.getFlag is not a function
[Detected 1 package: token-factions]
    at Function.AddBorderToggle (modules/token-factions/module/tokenFactions.js:134:83)
    at modules/token-factions/module/Hooks.js:113:27
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at TokenHUD._render (foundry.js:3117:13)
    at async TokenHUD._render (foundry.js:52464:4)

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Browser:** Edge
 - 

**Foundry Version:** V9.249

**Game System:** SWADE v1.02

**Comment by p4535992** [comment]
Should be fixed on 0.2.17
